# FROM public.ecr.aws/lambda/python:3.12
FROM python:3.12.3-alpine3.20
RUN mkdir /workspace
WORKDIR /workspace
COPY .devcontainer/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# RUN apk add --no-cache \
#     curl \
#     unzip \
#     groff \
#     less

# # Install AWS CLI v2
# RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
#     && unzip awscliv2.zip \
#     && ./aws/install \
#     && rm -rf awscliv2.zip aws
COPY . /workspace